CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Ambientes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" text NOT NULL,
    CONSTRAINT "PK_Ambientes" PRIMARY KEY ("Id")
);

CREATE TABLE "Criticidades" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" text NOT NULL,
    "Cor" text NOT NULL,
    "Peso" integer NOT NULL,
    "Downtime" boolean NOT NULL,
    "Descricao" text NOT NULL,
    CONSTRAINT "PK_Criticidades" PRIMARY KEY ("Id")
);

CREATE TABLE "TiposIncidente" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" text NOT NULL,
    "Descricao" text NOT NULL,
    CONSTRAINT "PK_TiposIncidente" PRIMARY KEY ("Id")
);

CREATE TABLE "Segmentos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" text NOT NULL,
    "AmbienteId" integer NOT NULL,
    CONSTRAINT "PK_Segmentos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Segmentos_Ambientes_AmbienteId" FOREIGN KEY ("AmbienteId") REFERENCES "Ambientes" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Incidentes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DataHoraInicio" timestamp with time zone NOT NULL,
    "DataHoraFim" timestamp with time zone,
    "TipoIncidenteId" integer NOT NULL,
    "AmbienteId" integer NOT NULL,
    "SegmentoId" integer NOT NULL,
    "CriticidadeId" integer NOT NULL,
    "Descricao" text NOT NULL,
    "AcoesTomadas" text NOT NULL,
    "DuracaoMinutos" integer,
    CONSTRAINT "PK_Incidentes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Incidentes_Ambientes_AmbienteId" FOREIGN KEY ("AmbienteId") REFERENCES "Ambientes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Incidentes_Criticidades_CriticidadeId" FOREIGN KEY ("CriticidadeId") REFERENCES "Criticidades" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Incidentes_Segmentos_SegmentoId" FOREIGN KEY ("SegmentoId") REFERENCES "Segmentos" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Incidentes_TiposIncidente_TipoIncidenteId" FOREIGN KEY ("TipoIncidenteId") REFERENCES "TiposIncidente" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Metas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AmbienteId" integer NOT NULL,
    "SegmentoId" integer NOT NULL,
    "Peso" integer NOT NULL,
    "MTTRMetaHoras" double precision NOT NULL,
    "SuperacaoMTTR" boolean NOT NULL,
    "MTBFMetaHoras" double precision NOT NULL,
    "SuperacaoMTBF" boolean NOT NULL,
    "MTBFMetaDias" double precision NOT NULL,
    "DisponibilidadeMeta" double precision NOT NULL,
    CONSTRAINT "PK_Metas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Metas_Ambientes_AmbienteId" FOREIGN KEY ("AmbienteId") REFERENCES "Ambientes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Metas_Segmentos_SegmentoId" FOREIGN KEY ("SegmentoId") REFERENCES "Segmentos" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Incidentes_AmbienteId" ON "Incidentes" ("AmbienteId");

CREATE INDEX "IX_Incidentes_CriticidadeId" ON "Incidentes" ("CriticidadeId");

CREATE INDEX "IX_Incidentes_SegmentoId" ON "Incidentes" ("SegmentoId");

CREATE INDEX "IX_Incidentes_TipoIncidenteId" ON "Incidentes" ("TipoIncidenteId");

CREATE INDEX "IX_Metas_AmbienteId" ON "Metas" ("AmbienteId");

CREATE INDEX "IX_Metas_SegmentoId" ON "Metas" ("SegmentoId");

CREATE INDEX "IX_Segmentos_AmbienteId" ON "Segmentos" ("AmbienteId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250724233717_InitialDashboardSchema', '9.0.7');

COMMIT;

